---
title: "Programming Assignment 3: Quiz"
author: "Marcio Woitek"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Source the files containing the solution to the assignment
source("best.R")
source("rankhospital.R")
source("rankall.R")
```

# Solution

## Question 1

```{r question_1, message=FALSE}
best("SC", "heart attack")
```

## Question 2

```{r question_2}
best("NY", "pneumonia")
```

## Question 3

```{r question_3}
best("AK", "pneumonia")
```

## Question 4

```{r question_4}
rankhospital("NC", "heart attack", "worst")
```

## Question 5

```{r question_5}
rankhospital("WA", "heart attack", 7)
```

## Question 6

```{r question_6}
rankhospital("TX", "pneumonia", 10)
```

## Question 7

```{r question_7}
rankhospital("NY", "heart attack", 7)
```

## Question 8

```{r question_8}
r <- rankall("heart attack", 4)
as.character(subset(r, state == "HI")$hospital)
```

## Question 9

```{r question_9}
r <- rankall("pneumonia", "worst")
as.character(subset(r, state == "NJ")$hospital)
```

## Question 10

```{r question_10}
r <- rankall("heart failure", 10)
as.character(subset(r, state == "NV")$hospital)
```
